steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spot-finder-api', '-f', 'Dockerfile.prod', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spot-finder-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spot-finder-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/spot-finder-api'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'API_KEY=${_API_KEY},GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY},CUSTOM_SEARCH_API_KEY=${_CUSTOM_SEARCH_API_KEY},CUSTOM_SEARCH_CX=${_CUSTOM_SEARCH_CX},GOOGLE_API_KEY=${_GOOGLE_API_KEY},GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'

images:
  - 'gcr.io/$PROJECT_ID/spot-finder-api'
