FROM python:3.12.3-slim

WORKDIR /app

# 依存関係ファイルをコピー
COPY requirements.txt .

# 依存関係のインストール
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションのソースコードをコピー
COPY ./app ./app

# Cloud Run用の環境変数設定
ENV PORT=8080
ENV HOST=0.0.0.0

# アプリケーションの起動
CMD uvicorn app.main:app --host $HOST --port $PORT --workers 1
